### ISSUE TITLE
Document how to run logic after returning a response

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#12]
Like when caching:

```
let resp = fetch("...")
inSweetNonBlockingFashion(function(){ cache.put(req, resp) });
return resp
```

**Comment by jeromegn** [comment]
Do we need to document this or is it fine since the recent "runtime" changes? (more intuitive)

**Comment by mrkurt** [comment]
I'm not clear on if a promise without `await` works well for this, or people would be better off with `setTimeout`. They both seem to work now, though, so probably less docs needed.
