### ISSUE TITLE
Package @fly/* separately

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#141]
Anything we have people requite with `import <name> from "@fly/<lib>"` is useful outside the Fly runtime. It could actually be a pretty nice set of core "Edge APIs". We should package it up separately for NPM at the very least, but also maybe deno — which means making versioned modules available over https one by one.

**Comment by mrkurt** [comment]
`@fly/image` relies on bridge functions. We can extract those into an "adapter" and, in theory, you could write an adapter to use `@fly/image` in Deno or any other environment.

**Comment by Siilwyn** [comment]
Would this also separate the CLI from the core? Then yes please! I'd like to deploy and create domains with fly programatically but including the whole CLI takes too much space (220 MB) and time to install because of the native/nodegyp requirement from `v8env`.

**Comment by Siilwyn** [comment]
@mrkurt thanks for the fast reply, I was thinking about that. Using your TS code is a lot nicer ofc. because then I don't need to 'duplicate' it. Looking at the API docs page I'm missing information about deployments, these are all about domains or am I overlooking something?
