### ISSUE TITLE
Allow more headers in responseCache

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#144]
The built in `responseCache` whitelists headers. This is confusing if an app sends custom headers since they can get lost after caching.

We could solve this in a bunch of ways:

* Configurable header allow-list
* Switch to a blocked header list (we shouldn't ever cache `Authorization`, maybe anything else goes?)
* Option on `set` to include certain headers

**Comment by michaeldwan** [comment]
I think a blacklist makes the most sense. Clients can remove a header that shouldn't be cached but a whitelist is a dead end and anything else complicates the API.

**Comment by mrkurt** [comment]
Also my bad, we should say "allowed"/"blocked" instead. Much more decent language.

**Comment by mrkurt** [comment]
Seems like the best current option could be configurable blocked list (maybe just `Authorization` and `Set-Cookie`) with a configurable allow list.

**Comment by mrkurt** [comment]
Done in #159!
