### ISSUE TITLE
Proposal: Multiple apps through static config

### ISSUE THREAD

**Issue by jeromegn** [superfly/fly#150]
There are plans in motion to completely open sourcing fly. Including the, currently closed source, code we use to run multiple apps on the same server.

Right now we use service discovery via a replicated database to store all the apps we can run in our service. This is not practical for running multiple apps locally.

This is a proposal to allow using a static configuration file (think haproxy or _maybe_ nginx) to run multiple apps, including simple rules for routing requests to specific apps.

There are a few things to consider:
- What format would the configuration file take?
- We'll need a new "interface" for plugging in multiple ways of retrieving apps according to certain criteria.
- Instructions for setting up some DNS resolution locally.
- Should we allow routing rules with criteria other than hostname? This would deviate from what we currently offer at Fly and might therefore not be compatible with our hosted service.

Discussions warmly welcomed!

**Comment by michaeldwan** [comment]
I had to fake this in #152 by monkey patching the networking apis. Native support would be much better.
