### ISSUE TITLE
Find better names for core, v8env, etc

### ISSUE THREAD

**Issue by michaeldwan** [superfly/fly#157]

**Comment by mrkurt** [comment]
I think I would do this:

* runtime <-- native stuff, possibly CLI
* web-api <-- `fetch`, `Response`, etc
* fly-api <-- `image`, `cache`, anything special to us

The `fly-api` is something I think we can publish/extract on its own someday. The `web-api` is gonna be heavily coupled to our runtime, but nice to have in one place.

**Comment by mrkurt** [comment]
This is probably not all that necessary anymore, we can make a new one when the time comes.
