### ISSUE TITLE
Fix doc generation

### ISSUE THREAD

**Issue by michaeldwan** [superfly/fly#160]
Just need to update paths

**Comment by mrkurt** [comment]
Should be mostly ready here: https://github.com/superfly/fly/commit/f3bcb438fcefc53816cfcecf66cb720bfbece74e

**Comment by michaeldwan** [comment]
Cool, that's a good solution. Nice work!

I made a few changes to work with the package structure:
- `publish-docs.sh` is nested under `packages/v8env` but can move back out later when we start publishing api docs for the other packages
- Generate docs from the repo root with `yarn doc` instead of `yarn doc:v8env` -- this will run `yarn doc` in each package that contains the `doc` script
- I moved the working directory to `packages/v8env/doc` because `dist/*` is being bundled for the npm package and I'd rather not add more logic to packing and npmignore
