### ISSUE TITLE
Header implementation is janky

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#162]
Our header implementation isn't complete, and needs some reworking to match the spec: https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers

We're currently using some very early JS for this, it could be much better and idiomatic TypeScript: https://github.com/superfly/fly/blob/master/v8env/src/headers.ts

**Comment by mrkurt** [comment]
When this is done, we can improve the header handling in `responseCache`.

**Comment by jphenow** [comment]
I think we can clooooose this now? 

mostly thanks to @michaeldwan for cleaning up my mess 😬 👏
