### ISSUE TITLE
"@fly/fly@0.42.0-pre.3" has no binaries

### ISSUE THREAD

**Issue by benswinburne** [superfly/fly#167]
Having installed with yarn (granted the example uses npm)

I get the following error

> ...
> "@fly/fly@0.42.0-pre.3" has no binaries
>  Done in 17.84s.

Which obviously results in an inability to run any fly commands.

    # ~/playground: which fly
    # ~/playground:

Is this a bug or simply me doing something wrong?

**Comment by mrkurt** [comment]
That was a bug, that's a prerelease version NPM somehow picked up as a real release. Will you try installing it again? You should get 0.41.0.

Also you'll need to make sure you get `yarn global` to get the executables in the right place.

**Comment by benswinburne** [comment]
> success Installed "@fly/fly@0.41.0" with binaries:
>      - fly

👍 

    # ~/playground which fly
    /Users/###/.npm-packages/bin/fly

👍 

Thanks

**Comment by mrkurt** [comment]
https://cultofthepartyparrot.com/parrots/hd/parrot.gif
