### ISSUE TITLE
Caching by location or region

### ISSUE THREAD

**Issue by MarcFor99** [superfly/fly#179]
Hi,

Would there be the possibility of limiting the caching to only running from certain areas or regions? In the UK with GDPR regulations there is a requirement to not allow data to be stored outside of the Europe. 

Marc.

**Comment by mrkurt** [comment]
You can! `app.region` isn't well documented but it stores the airport identifier for the region it's in. You can use that for all kinds of logic, and even go so far as to serve up different content for different places.

That said, GDPR should allow data to be stored outside the EU as long as you have a data processor agreement in place. We're happy to help with that if you get going, but for dev purposes I'd just use the `app.region` logic.

**Comment by MarcFor99** [comment]
That's great, thank you @mrkurt 

Marc.
