### ISSUE TITLE
Can't Install @fly/fly with npm or yarn

### ISSUE THREAD

**Issue by traversng** [superfly/fly#186]
Can't install @fly/fly with npm nor yarn.

- Node versions: 10.10, 10.8.0, 9.11, 8.9.4, 7.9.4 (Many other versions as well)

- NVM version: 0.33.2, Yarn version: 1.10.1

- NPM version: 6.2.0

- NPM Error: node-gyp rebuild hangs

- Yarn Error: travis@MacBook-Pro flyio $ yarn global add @fly/fly
yarn global v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-airbnb@15.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
[4/4] 📃  Building fresh packages...
[1/9] ⠐ fsevents
[6/9] ⠐ isolated-vm
[-/9] ⠐ waiting...
[4/9] ⠐ integer
warning Error running install script for optional dependency: "/Users/travis/.config/yarn/global/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/travis/.config/yarn/global/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@10.9.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.9.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.9.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | darwin | x64
gyp gyp info ok
info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv: line 145: /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv-exec: Argument list too long
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:599:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command \"/Users/travis/.nvm/versions/node/v10.9.0/bin/node\" \"/Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
gyp ERR! cwd /Users/travis/.config/yarn/global/node_modules/fsevents
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/travis/.nvm/versions/node/v10.9.0/bin/node /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/travis/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command \"/Users/travis/.nvm/versions/node/v10.9.0/bin/node\" \"/Users/travis/.config/yarn/global/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/travis/.config/yarn/global/node_modules/fsevents
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/Users/travis/.nvm/versions/node/v10.9.0/bin/node /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv: line 145: /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv-exec: Argument list too long
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:599:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command \"/Users/travis/.nvm/versions/node/v10.9.0/bin/node\" \"/Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/travis/.config/yarn/global/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64\"
gyp ERR! cwd /Users/travis/.config/yarn/global/node_modules/fsevents
[-/9] ⠠ waiting...
[6/9] ⠠ isolated-vm
[-/9] ⠠ waiting...
[4/9] ⠠ integer
error /Users/travis/.config/yarn/global/node_modules/segfault-handler: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/travis/.config/yarn/global/node_modules/segfault-handler
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.9.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv: line 145: /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv-exec: Argument list too long
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:599:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/travis/.nvm/versions/node/v10.9.0/bin/node" "/Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/travis/.config/yarn/global/node_modules/segfault-handler

**Comment by mrkurt** [comment]
Huh, those `Argument list too long` errors are interesting. This happens both with and without `-g`?

**Comment by mrkurt** [comment]
I can't replicate this at all. It works with every version of node I install with nvm. But those errors don't look like nvm exactly, they look like some modules are getting really long paths.

**Comment by traversng** [comment]
@mrkurt when I get home, Ill try installing without -g. Other than that, I'll need to spend more time on it. Pretty 😞

**Comment by mrkurt** [comment]
Let us know if you get more info on this! I can't replicate it.
