### ISSUE TITLE
Modularize app build logic

### ISSUE THREAD

**Issue by Siilwyn** [superfly/fly#189]
In the vein of https://github.com/superfly/fly/issues/141 I'm proposing to publish `core/src/utils/build.ts` as a module `@fly/build`. The logic to 'get' the webpack config and compile the assets is something I have [mostly duplicated 1:1 in my app](https://github.com/voorhoede/plek/blob/a8e383d8bf6d9ef9f6cd4aa7d98f3bb059d51df8/packages/cli/src/fly.js#L21-L93). Since it's quite specific and `build.ts` doesn't seem to have many internal dependencies it seems like a good fit and starting point.

Thoughts on this?

Two internal imports are:
- `import log from "../log"`
- `import { v8envModulePath } from "../v8env"` since `v8env` in turn imports `isolated-vm` it becomes quite big.

How to handle these, any ideas? They both are only a few lines of code, since `v8envModulePath` is only used in test and actually appended with a path the most pragmatic solution would be to inline it in my opinion.

**Comment by mrkurt** [comment]
This sounds like a great idea to me, I'm all for it. I think it will be pretty straightforward with our lerna setup too. If you feel like tackling it I'd be happy to merge + ship a new version.
