### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by jeromegn** [superfly/fly#19]
They're pretty useful!

Still need to figure out the exact API, definitely going to look up the proper spec for it. Maybe part of the `fly` namespace like:

```javascript
fly.ws.on("connect", function(conn){
  conn.on("message", function(message){
    // echo
    conn.send(message)
  })
});
```

edit: Far more details below.

The reality of this is that v8 contexts (where code runs) are disposable. In development they're disposed after every request to simulate worst-case scenarios. In production they will likely stick around for a long time until you or we deploy a new version, memory usage grows too much, or you don't get enough traffic to keep your runtime alive.

There are many ways to go about this:

*Each context is kept alive during the lifetime of a connection*

Which is currently the case, but we'd have to change things around a bit for websocket connections I think.

Since each context would be disconnected from the other ones, it would be harder to broadcast something to all connected clients. It would most certainly have to be triggered by an external event that can be caught by other servers too.

We can technically scale to a large amount of contexts per v8 isolates, but each context uses a minimum amount of heap (it's roughly equal to the size of our global object.) People would run out of heap very quickly.

*Multiple connections per context*

A context could handle multiple connections concurrently. That would be a very different way of working with contexts than we currently do. Right now a context can only handle a single connection concurrently. We'd have to change the logic here, but only for the websocket protocol.

Contexts don't communicate (yet) with each other. Broadcasting would be hard. Contexts will eventually be able to communicate via shared memory (SharedArrayBuffer,) but we don't currently support this feature. Same issue than the first solution across servers.

*Connections handled outside of contexts*

The server keeps websocket connections outside of v8 contexts. Each context can receive and send messages via events (like the `FetchEvent`, but different.)

No need to communicate across contexts, bridged functions work across contexts.

---

There are a lot of challenges, here are some:

- Handle server restarts, reconnecting websocket clients
- Memory management (each connection uses some amount of memory)
- Broadcasting across servers

---

I think websockets will have to wait a little bit. We can't do them properly yet. We might add a mechanism for triggering "notifications" across servers and then this feature might be more realistic.

**Comment by gdi2290** [comment]
you should also checkout this thread
https://github.com/w3c/ServiceWorker/issues/947
