### ISSUE TITLE
URL parsing dependency of v8env is outdated

### ISSUE THREAD

**Issue by Siilwyn** [superfly/fly#191]
The `universal-url-lite` dependency that [was introduced to save size](https://github.com/superfly/fly/commit/5a375e56079dc05d77293912bd6a2748744208b3) is causing problems on `npm install` when used in a project that uses Babel 7 and up. This is [a known issue](https://github.com/stevenvachon/universal-url-lite/pull/17) but the fact that this project uses some custom post install scripts is already a red flag.

Comparing the size with the latest version of `whatwg-url` it even seems worse:
https://packagephobia.now.sh/result?p=whatwg-url
https://packagephobia.now.sh/result?p=universal-url-lite

I think reverting to `whatwg-url` would be a good idea, thoughts?

**Comment by mrkurt** [comment]
Version 0.44.1 includes the fix for this!
