### ISSUE TITLE
Links to the Fly v8env primary APIs are broken; can't find new location

### ISSUE THREAD

**Issue by WesleyDavid** [superfly/fly#209]
Requests abound for information about the API that the Fly runtime provides. Some documentation exists here: https://github.com/superfly/fly/tree/master/packages/v8env

Specifically: https://github.com/superfly/fly/tree/master/packages/v8env#primary-apis

Those links don't point to files that seem to exist _anywhere_ now. Anyone remember what happened to it and what the intention was?

**Comment by mrkurt** [comment]
Those should link to URLs like this, not sure how they regressed: https://fly.io/docs/apps/api/modules/fly_cache.html
