### ISSUE TITLE
support for --unstable flag in Deno.

### ISSUE THREAD

**Issue by devYusuf** [superfly/fly#268]
I tried to deploy a deno app today, I ran into unstable errors which would be solved by the --unstable flag

**Comment by codepope** [comment]
Assuming that this is with the Builder, add --unstable to the .permissions file - it is injected into the command line for the image.

**Comment by devYusuf** [comment]
I did that. It doesn't work

**Comment by codepope** [comment]
What error are you getting?

**Comment by codepope** [comment]
The buildpack has been updated. If you try again, you should not see it error out.
