### ISSUE TITLE
Continuous Deployment with Buildkite

### ISSUE THREAD

**Issue by karllhughes** [superfly/fly#281]
Just to clarify, would this be an article about how to use Buildkite to deploy to Fly? Or how to run Buildkite _on_ Fly?

My initial thought was the first one, but I wanted to check before I sent an outline over. Thanks!

**Comment by mrkurt** [comment]
How to deploy _to_ Fly with Buildkite. Someday we'll want the latter. :)

**Comment by karllhughes** [comment]
Perfect, that's what I thought. 😁

Here's an outline:

- Introduction
  - What is CD? Why it's important? (Just briefly)
  - What is Buildkite? Why use it for CI/CD?
  - Why host on the edge? Why Fly? (Again, briefly but I think it's important to give context)
- How to Deploy to Fly using Buildkite
  - Installing Buildkite - Will just reference their installation instructions as this varies depending on the user's hosting provider: https://buildkite.com/docs/agent/v3/installation
  - A simple app to deploy to Fly (I'm thinking just a little Node-based "Hello World") script
  - Introduction to Pipelines: https://buildkite.com/docs/pipelines
  - Setting up a Pipeline, steps, yaml file, etc: https://buildkite.com/docs/pipelines/defining-steps
  - Testing that it works: make a change, re-deploy it, see the change
- Conclusion

**Comment by karllhughes** [comment]
Moved to Fly Discord: https://community.fly.io/t/continuous-deployment-with-buildkite/78
