### ISSUE TITLE
Running Varnish on Fly

### ISSUE THREAD

**Issue by karllhughes** [superfly/fly#282]
Here's an outline of what I'm thinking:

- Introduction
  - What is Varnish? Why use it?
  - How does Varnish work? - Nothing super in-depth, but I think it's important to understand how Varnish works at a high level to use it properly
  - Why host Varnish on the Edge with Fly? - Performance - not only do you get the performance benefits of Varnish, you also lower latency by serving it on the edge.
- How to deploy Varnish to Fly
  - Creating a new Fly App
  - Setting up the Dockerfile (based on https://hub.docker.com/_/varnish)
  - Creating a Varnish config file (VCL)
  - Connecting Varnish to a backend service - will probably use an [open API from this list](https://github.com/public-apis/public-apis)
  - Benchmarking the performance improvement by going through Varnish - compare the original API to a call to Varnish on Fly
- Conclusion

**Comment by mrkurt** [comment]
Nice. I think for stuff like Varnish, the "easiest" backend source is an s3 bucket or similar. Varnish is useful for doing CDN like caching and that means (I think) that showing people how to work with static files makes the most sense.

**Comment by karllhughes** [comment]
Moved to discord: https://community.fly.io/t/running-varnish-on-fly/82
