### ISSUE TITLE
Secured API Key generation on the edge with Fly

### ISSUE THREAD

**Issue by karllhughes** [superfly/fly#283]
This wasn't on your target list, but it's a problem I came across recently that would make a good Fly use case.

Algolia is a managed search service. They host your index on a globally distributed network (so it's fast), but if you want to authenticate users, you have to generate a temporary key for them (https://www.algolia.com/doc/guides/security/api-keys/#secured-api-keys).

This means your first call will require a full trip to your backend authentication server, but you can speed that up using edge computing.

Any interest in this becoming an article for Fly?

**Comment by mrkurt** [comment]
Yep! This would be a good one. They even say this in the docs:

> Secured API keys are virtual, which means they aren’t stored anywhere, and you can’t find them on the Algolia dashboard. You generate them _on the fly_

Building little gateways to other services is a good use of Fly.

**Comment by karllhughes** [comment]
Moved to Discord: https://community.fly.io/t/secured-api-key-generation-on-the-edge-with-fly/86
