### ISSUE TITLE
Implement Body#json()

### ISSUE THREAD

**Issue by jeromegn** [superfly/fly#32]
We already have `.text()` and `.arrayBuffer()`.

Should be fairly easy to produce an Object from a JSON source.

**Comment by mrkurt** [comment]
Like this? 

https://github.com/superfly/fly/blob/body-refactor/v8env/ts/body_mixin.ts#L64-L66

**Comment by jeromegn** [comment]
Yes, like that. You get to close an extra issue once your PR is merged.

**Comment by jeromegn** [comment]
Implemented in #30
