### ISSUE TITLE
Add test coverage to v8env tests

### ISSUE THREAD

**Issue by mbyczkowski** [superfly/fly#35]
Since any `v8env_test` tests are run programmatically with mocha, we don't get code coverage reports for them. We might need to do something like https://github.com/gotwarlost/istanbul/issues/394, but:
- with the caveat that istanbul JS file with all its dependencies can be added to the test runner (I think) - https://github.com/superfly/fly/blob/master/src/cmd/test.ts#L12
- and hooked into mocha run - https://github.com/superfly/fly/blob/master/v8env/testing/run.js#L5

**Comment by mrkurt** [comment]
Donesies
