### ISSUE TITLE
Body can't handle Uint8Array

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#38]
```
new Response(new Uint8Array())
```

**Comment by pudility** [comment]
I would love to see if I can fix this one. I assume the issue would be somewhere in [server.ts](https://github.com/superfly/fly/blob/master/src/server.ts) - but I am really not sure. Would you mind pointing out where fly creates the body or where the error happens?

**Comment by mrkurt** [comment]
Oh nice, this is a good one to start with. The relevant file is here: 

https://github.com/superfly/fly/blob/master/v8env/ts/body_mixin.ts

That's the class we use to represent Request/Response bodies within the v8 environment. They support ArrayBuffers just fine, so making this work should just be a matter of a test + setting `bodySource` properly at create time.

The best place for a test condition is probably here: https://github.com/superfly/fly/blob/master/v8env_test/request.spec.js

**Comment by jeromegn** [comment]
Hey @pudility, there's a lot going on, we should probably document the architecture, for now I can try to explain it here.

We're using a package called [isolated-vm](https://github.com/laverdet/isolated-vm) to isolate user's code. We also refer to it as `ivm`, for short.

We can only send primitives back and forth (string, number, boolean, null, undefined), the rest needs to be either wrapped in a `ivm.Reference` or `ivm.ExternalCopy`. Both of those can be transferred from node ("default v8") to a non-default v8 (user's code.)

There are some exceptions, we can also transfer "pointers" to raw array of bytes structures. This includes `ArrayBuffer`, `Uint8Array`, and all other [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) types.

You're right about `server.ts`, it does need to handle the response body type of Uint8Array. It doesn't look like that's the case right now according to this: https://github.com/superfly/fly/blob/master/src/server.ts#L149 (that's used in the `handleResponse` function.

You'll want to make sure you can also send a Uint8Array from a non-default v8. That would be in `v8env/events.js` I believe. That's where `event.respondWith` is handled. Feel free to ask here or in slack for more help!

**Comment by pudility** [comment]
Sounds good - I will try to figure this out and if I have any questions I will make sure to ask. Thanks for all the explanations of how it works @jeromegn and for the links @mrkurt.

**Comment by pudility** [comment]
So just to be clear - I should write a method similar to the [`arrayBuffer`](url) method for `Uint8Array`. then update `server.ts` to also be able to handle `Uint8Array` responses. Then test it and see what else needs to be done? 

Also I assume that I would need to tie it in some other way - it looks like the `BodyMixin` class is imported in `v8env/index.js` - do I need to do anything for that?

**Comment by jeromegn** [comment]
Oh, that's when the [Fetch spec](https://fetch.spec.whatwg.org/) comes in. We want to be compliant with relevant whatwg specs. Your link to `arrayBuffer` didn't work, but I assume you were referring to the `Body.prototype.arrayBuffer` function.

I think what we want to do if handle Uint8Array bodies like we do here: https://github.com/superfly/fly/blob/master/v8env/events.js#L99-L107

- If the body has a `_ref`, it means it's a `ProxyStream`, which we can handle in a special way in node, in `server.ts`.
- If the body is a string, send as-is.
- Else, convert to arrayBuffer.

^^^ That's the current behaviour.

There are 2 options here (I think):
- The body mixin's `arrayBuffer` function could detect if it's a typed array and do `bodySource.buffer` to get the underlying `ArrayBuffer`, here are some docs about that: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/buffer
- We can add a branch to the conditional in the lines I referenced in `v8env/events.js` to handle typed arrays and do the same thing (get their `.buffer`)

I think modifying the BodyMixin may be the cleanest solution.

**Comment by pudility** [comment]
I think I understand now. Thanks for clearing it up a bit. I will try implementing the first option.

**Comment by pudility** [comment]
@jeromegn do you know if there is any way to get an `ArrayBuffer` from a `SharedArrayBuffer`?

**Comment by jeromegn** [comment]
I'm not sure, but I think you can ignore this one for now :) We don't support them at the moment (we'd need to run node.js with a special flag, or upgrade to node.js > 8.)

**Comment by pudility** [comment]
I see. In that case, I think I have something that would work.
```JavaScript
if (this.bodySource instanceof Uint8Array) {
  const buffer = this.bodySource.buffer
  if (buffer instanceof ArrayBuffer) return buffer
}
```
When I ran it it passed the tests - is there anything else that I would need to do?

**Comment by jeromegn** [comment]
Submit a PR 😄

If you want, you can add more conditionals for other types that are TypedArrays. It's a long list though. It's fine if you want to make a small PR that addresses only this specific type.

If possible, test it "throughout" by creating a test in the `test/`. You can also submit your PR and I can comment there, it's easier when I can see all the code.

**Comment by pudility** [comment]
Sounds good! I will make a test then submit a PR and work on some of the other types.

**Comment by pudility** [comment]
@jeromegn quick question about the test - do you want me to put it in `test/` or `v8env_test/request.spec.js`?

**Comment by jeromegn** [comment]
We've been putting unit tests in `v8env_test`. Those tests only test stuff "inside" v8.

`test/` is where integration (or "end to end") tests are. They usually involve creating fixture (fake) apps under `test/fixtures/apps` and using `before` and `after` functions from mocha to start and stop a server which only runs a specific app. Then you can hit it with a request and test if the response is as expected.

In this case, you'd want to know if you're getting the same bytes you sent in, in the response. You can make a Uint8Array representing a specific message and then test that the response.data is that message.

There are a lot of examples in `test/server.spec.ts` to inspire from 😄 

(I'm sorry if I'm over-explaining things here, I tend to be thorough when writing!)

**Comment by pudility** [comment]
@jeromegn Thanks for the explanation. I do not think you are over explaining at all - I like to know as much as I can.

**Comment by jeromegn** [comment]
On second thought, you might not need an end-to-end test. I think we're already testing we can handle an `ArrayBuffer` which your implementation would be sending.
