### ISSUE TITLE
CLI flags don't work after subcommands

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#58]
This works: `fly --app asdf deploy`

This does not: `fly deploy --app asdf`

It would be nice if those args worked even after the subcommand.

**Comment by pudility** [comment]
I will get to work on this.

**Comment by pudility** [comment]
It looks like this might be more of an issue with [commandpost](https://github.com/vvakame/commandpost) than with fly. I think it has to do with the order of `subCommand` and `option` on `root`.

**Comment by mrkurt** [comment]
Yeah it might be something we should do a commandpost PR for. I haven't looked too closely, but we could also define "global" params and just include them on each subcommand too.

To be honest, I don't think we necessarily have to support `fly --app deploy`, if we can make the subcommands take the right sets of arguments instead that'd be 👌.

**Comment by pudility** [comment]
I have been re-writing the `cmd` directory a little bit. I think we should use [commander](https://github.com/tj/commander.js) instead, it seems to work much better and it supports commands in any order. 

I have something that was working but then I got [this](https://github.com/tj/commander.js/issues/786) error, so I have an issue open - but after that gets sorted out it should be good to go.

**Comment by jeromegn** [comment]
We used to use commander, but there were some troubles with it. I can't exactly remember though.

commandpost has types which is nice.

Heroku also made a nice one: https://github.com/oclif/oclif if that's better suited (no idea.)

**Comment by pudility** [comment]
I will check that out, Thanks.

**Comment by jeromegn** [comment]
@pudility it's also possible to use inheritance with commandpost. For instance, every subcommand's options could inherit from the root options. This way, every subcommand could accept all global options. There are other challenges too, like getting the app ID from one place. I don't know how well it would render in the CLI help text either.

I see you got a branch going, I briefly looked at it. If it solves the issue feel free to disregard ^ :)

**Comment by jeromegn** [comment]
This is fixed in `0.28.3`
