### ISSUE TITLE
Add example apps

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#60]
We don't have many example apps in this repo, we should!

Some interesting ones:

- [ ] HTTP caching demo: use `fetch` and the [Web Cache API ](https://github.com/superfly/fly/blob/master/v8env/cache.js)(`add/put/match`) to do basic HTTP caching
- [ ] HTML parsing/modification demo using `fetch` and the [`Document.parse`](https://github.com/superfly/fly/blob/master/v8env/document.js) interface to modify HTML.
- [ ] Image resizing demo using the `fly.Image` API to scale images down or convert them to webp
- [x] Watermark demo for #55

**Comment by pudility** [comment]
@mrkurt how does fly make an HTML response?

**Comment by OKNoah** [comment]
I have a bit of a caching app example here. Don't mind constructive feedback, first go at it: https://github.com/superfly/fly/pull/75

**Comment by mrkurt** [comment]
Gonna replace this with specific app example ideas.

**Comment by OKNoah** [comment]
lol
