### ISSUE TITLE
fly.http.respondWith/fetch event should have better errors

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#65]
The error is a little ambiguous when you return the wrong thing like this:

```
fly.http.respondWith(()=> "wat")
```

**Comment by jeromegn** [comment]
Agreed.

What's the errors currently? Does it refer to the fetch event and not to fly.http.respondWith?

**Comment by mrkurt** [comment]
Yeah, it's not entirely bad, but `fetch` and the fetch event are ambiguous:

```
error: [Error: Invalid response type for 'fetch' event. Expecting a straight Response, a function returning a Promise<Response> or a Response.] undefined
2018-04-10T16:31:07.702Z - error: error from fetch callback: Error: Invalid response type for 'fetch' event. Expecting a straight Response, a function returning a Promise<Response> or a Response.
```

**Comment by pudility** [comment]
For what its worth, I know that when I am trying to debug something its always nice to have the line number. I am not sure if that is possible here but, it would be nice.

**Comment by pudility** [comment]
I was wondering about using something like [this module](https://www.npmjs.com/package/pretty-error) - what do you think?

**Comment by mrkurt** [comment]
This is in v8env, so we can't/shouldn't use an npm for it.

That particular error is hard to nail down to a line number. Basically what happens is:

```
fly.http.respondWith(function(req){
    let resp = 23 // not a valid response
    /* lots of logic */
    return resp
})
```

The return value is syntactically correct, so Javascript doesn't error, but it's not what we expect back from that function. I have a quick fix locally I'll push today. 🎉
