### ISSUE TITLE
Data must be an ArrayBuffer

### ISSUE THREAD

**Issue by bberak** [superfly/fly#69]
Hi there,

First of all, I'm really excited to try out your service..

I'm trying to follow the 'optimize images' example here: https://fly.io/articles/fly-edge-applications-global-javascript/ but am struggling to get it to work (I could be doing something silly).

Here is my index.js file:

```
fly.http.respondWith(async req => {
	const resp = await fetch("https://raw.githubusercontent.com/bberak/react-native-game-engine/master/logo.png");
	const original = new fly.Image(resp.arrayBuffer());

	let image = original.resize(200).withoutEnlargement();

	image = await image.toImage();

	return new Response(image.data, resp);
});
```

And here is the error I'm getting: 

```
2018-04-11T07:50:25.091Z - error: [Error: Data must be an ArrayBuffer] 'Error: Data must be an ArrayBuffer\n    at new Image (webpack:///v8env/ts/fly/image.ts:21:13)\n    at fly.http.respondWith (webpack:///index.js:3:1)\n    at <anonymous>'
2018-04-11T07:50:25.091Z - error: error from fetch callback: Error: Data must be an ArrayBuffer
```

I am using **fly v0.28.1**. I get this error when running on my **localhost** and from **edgeapp.net**. Let me know if I can provider further info.

Any help would be greatly appreciated.

Cheers!

**Comment by jeromegn** [comment]
Hi!

Looks like the article's example is wrong, it should be `await resp.arrayBuffer()` to get the actual ArrayBuffer. Else, this returns a Promise<ArrayBuffer>.

Will fix the article!
