### ISSUE TITLE
req.pathname

### ISSUE THREAD

**Issue by pudility** [superfly/fly#77]
This:
```JavaScript
req.pathname
```
Would be much cleaner than this (current solution):
```JavaScript
new URL(req.url).pathname
```

**Comment by mrkurt** [comment]
It _would_ but it's not part of the spec: https://developer.mozilla.org/en-US/docs/Web/API/Request

We've though about adding a `parsedURL` property to request (also not part of the spec) but it's complex to keep that consistent with the `url` property. For the moment I think we're better off just letting people create URL objects when they need them.

**Comment by pudility** [comment]
Sounds good.
