### ISSUE TITLE
Environments are janky

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#86]
Deploys are always "production", it's not currently possible to deploy and app + settings as a "staging" environment. This might just be a documentation issue, but it's not clear how people are supposed to use environments.

**Comment by jeromegn** [comment]
Not mis-documented, it's not implemented.

It probably wouldn't be a huge change to be honest. It's currently hard-coded to production (in production), but we could get it from the release somehow.

**Comment by robmadole** [comment]
I end up hand-editing my `.fly.yml` between staging and production. It's a scary moment when i `fly deploy`. This would be our #1 ask.

**Comment by mrkurt** [comment]
Right now you can add scripts in `package.json` to make this a little safer. In fact, you can remove `app` from the `.fly.yml` and then only the scripts in package.json will work:

```json
    "deploy:prod": "npx fly --app <app>-production deploy",
    "deploy:stage": "npx fly --app <app>-staging deploy",
```

Then run `npm run deploy:stage` or `npm run deploy:prod`. This might buy some time until we get good env support.

**Comment by robmadole** [comment]
Oh interesting. Yeah that's a good guard 👍

**Comment by jeromegn** [comment]
@robmadole btw I prereleased `0.33.3-1` with the fix for putting `-e` or `--env` anywhere in the sub commands chain.

**Comment by robmadole** [comment]
@jeromegn I'll upgrade our Pro CDN edge app. Thank you, sir.

**Comment by mrkurt** [comment]
This is out as of `0.34.x`.
