### ISSUE TITLE
fly deploy should "start" the app locally before it pushes

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#96]
There are a few fun ways of deploying broken apps, if we made `fly deploy` actually boot before it pushes it would fix a lot of that. So far we've seen:

1. App breaks post deploy when there's a typo in the env config (`production` has a typo, `development` does not, app works with fly server but fails once pushed)
2. Deploy before npm install: in this case, `fly server` fails but the deploy occasionally works.

**Comment by robmadole** [comment]
One danger I can think of here @mrkurt is that some of our production configs rely on key secrets that are only available on the edge servers. So the app might fail to boot in `production` environment in that case.

**Comment by mrkurt** [comment]
Yeah that's a good point. I think we can account for that, we can at least stub those with blanks or something. It's imperfect but probably better than nothing.

Thinking about this more, we could even force a test run before deploy.
